QUEUE_SUPPLY_STOCK_UPDATED: "qa-inventory-stock-updated"
QUEUE_PROCESSED: "qa-processed"
QUEUE_STATUS_UPDATED: "qa-status-updated"
QUEUE_SHIPMENT_SHIPPED: "qa-shipment-shipped"
QUEUE_RETURNS_RECEIVED: "qa-returns-received"
QUEUE_RECEIVING_RETURN_PROCESSED: "qa-receiving-return-processed"
QUEUE_TRANSFER_STATUS_UPDATED: "qa-transfer-status-updated"
QUEUE_RETURN_LABEL_CREATED: "qa-ms-shipping-return-label-created"
QUEUE_CONFIRMATION_EMAIL: "qa-confirmation-email"
QUEUE_WAREHOUSE_ITEM_ABANDONED: "qa-warehouse-item-abandoned"
QUEUE_PAYMENT_CAPTURE: "qa-payment-capture"
QUEUE_PAYMENT_REFUND: "qa-payment-refund"
QUEUE_PAYMENT_VOID: "qa-payment-void"
QUEUE_CUSTOMER_SHIPMENT_SHIPPED: "qa-customer-shipment-shipped"
QUEUE_WAREHOUSE_ABANDONED: "warehouse-abandoned"
QUEUE_PAYMENT_FAILED: "payment-failed"

REDIS_DB: "0" 
REDIS_HOST: "qa-redis"
REDIS_PORT: "6379"

MYSQL_DATABASE: "qa"
MYSQL_HOST: "qa"
MYSQL_USERNAME: "qa"
MYSQL_PASSWORD: "password"
MYSQL_PORT: "3306"