QUEUE_SUPPLY_STOCK_UPDATED: "qa-inventory-stock-updated"
QUEUE_PROCESSED: "qa-processed"
QUEUE_STATUS_UPDATED: "qa-status-updated"
QUEUE_SHIPMENT_SHIPPED: "qa-order-shipment-shipped"
QUEUE_RETURNS_RECEIVED: "qa-returns-received"
QUEUE_RECEIVING_RETURN_PROCESSED: "qa-receiving-return-processed"
QUEUE_TRANSFER_STATUS_UPDATED: "qa-transfer-status-updated"
QUEUE_RETURN_LABEL_CREATED: "qa-ms-shipping-return-label-created"
QUEUE_CONFIRMATION_EMAIL: "qa-confirmation-email"
QUEUE_WAREHOUSE_ITEM_ABANDONED: "qa-warehouse-order-item-abandoned"
QUEUE_PAYMENT_CAPTURE: "qa-payment-capture"
QUEUE_PAYMENT_REFUND: "qa-payment-refund"
QUEUE_PAYMENT_VOID: "qa-payment-void"
QUEUE_CUSTOMER_SHIPMENT_SHIPPED: "qa-customer-shipment-shipped"